wandb:
  offline: true
  project: VTC-IS-25
  name: train-whisper-small

data:
  dataset_path: data/baby_train
  classes:
  - KCHI
  - OCH
  - MAL
  - FEM
  dataset_multiplier: 1.0

audio:
  chunk_duration_s: 4.0
  sample_rate: 16000
  strict_frames: false

model:
  name: surgical_hydra
  config:
    encoder: whisper_small_encoder
    encoder_layers: []
    reduction: weighted
    lstm:
      hidden_size: 128
      num_layers: 4
      bidirectional: true
      dropout: 0.5
    classifier: 256

train:
  lr: 0.001
  batch_size: 32
  max_epochs: 100
  validation_metric: loss
  extra_val_metrics:
  - loss
  - f1_score
  profiler: null
  dataloader:
    num_workers: 8
  scheduler:
    patience: 3
