[project]
name = "vtc-is-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "segma",
]

[tool.uv.sources]
segma = { git = "https://github.com/arxaqapi/segma" }
